import { Request, Response } from "express";

export const generateProject = async (req: Request, res: Response) => {
  try {
    const { prompt } = req.body;

    const html = `
      <html>
        <head>
          <title>Generated Website</title>
          <style>
            body{
              margin:0;
              background:#000;
              color:white;
              font-family:Arial;
              text-align:center;
              padding:100px;
            }
            h1{
              font-size:60px;
            }
            p{
              color:#aaa;
              font-size:20px;
            }
          </style>
        </head>
        <body>
          <h1>${prompt}</h1>
          <p>Website generated by BuildStack AI</p>
        </body>
      </html>
    `;

    res.status(200).json({
      html,
    });
  } catch (error) {
    res.status(500).json({
      message: "Generation failed",
    });
  }
};