import { Request, Response } from "express";
import prisma from "../config/prisma";

export const saveProject = async (req: Request, res: Response) => {
  try {
    const { name, htmlCode } = req.body;

    const project = await prisma.project.create({
      data: {
        name,
        description: "Generated by BuildStack",
        htmlCode,
        cssCode: "",
        jsCode: "",
        userId: 1
      },
    });

    res.status(201).json({
      message: "Project saved successfully",
      project,
    });
  } catch (error) {
    res.status(500).json({
      message: "Save failed",
      error,
    });
  }
};